# -*- coding: utf-8 -*-
"""Customer Segmentation system.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gctnlwUPHvimCLOYlycRFn_VS-t4J3Wj
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

cust_data = pd.read_csv('/Mall_Customers.csv')

cust_data.head()

cust_data.shape

cust_data.info()

cust_data.isnull().sum()

X = cust_data.iloc[:,[3,4]].values
print(X)

wcss = []

for i in range(1,13):
  kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
  kmeans.fit(X)

  wcss.append(kmeans.inertia_)

sns.set()
plt.plot(range(1,13), wcss)
plt.title('The Elbow Point Graph')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.show()

kmeans = KMeans(n_clusters=5, init='k-means++', random_state=0)

Y = kmeans.fit_predict(X)

print(Y)

plt.figure(figsize=(10,10))
plt.scatter(X[Y==0,0], X[Y==0,1], s=50, c='purple', label='Cluster 1')
plt.scatter(X[Y==1,0], X[Y==1,1], s=50, c='black', label='Cluster 2')
plt.scatter(X[Y==2,0], X[Y==2,1], s=50, c='pink', label='Cluster 3')
plt.scatter(X[Y==3,0], X[Y==3,1], s=50, c='orange', label='Cluster 4')
plt.scatter(X[Y==4,0], X[Y==4,1], s=50, c='blue', label='Cluster 5')

plt.scatter(kmeans.cluster_centers_[:,0], kmeans.cluster_centers_[:,1], s=100, c='red', label='Centroids')

plt.title('Customer Groups')
plt.xlabel('Annual Income')
plt.ylabel('Spending Score')
plt.show()

